### ISSUE TITLE
Rotate the display during boot

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/pi-kiosk#3]
According to [this comment](https://www.youtube.com/watch?v=gpyYCTgJO88&lc=UgzRywz_l5WW92p9phF4AaABAg) on YouTube, it is possible to have the display rotated during boot (e.g. when the kernel commandline stuff is going past):

Add the following to `/boot/firmware/cmdline.txt`:

```
video=DSI-1:panel_orientation=right_side_up
```

I'll have to test this on my display!

**Comment by Jan69** [comment]
alternatively, according to [StackOverflow](https://raspberrypi.stackexchange.com/a/136596) you can put `fbcon=rotate:2` into `/boot/cmdline.txt` (which is the [well documented kernel option](https://www.kernel.org/doc/html/latest/fb/fbcon.html) to rotate the framebuffer console the boot log appears in)

**Comment by geerlingguy** [comment]
Test results:

  - `fbcon=rotate:2` didn't seem to make a difference
  - `video=DSI-1:panel_orientation=right_side_up` put it upside-down
  - `video=DSI-1:panel_orientation=left_side_up` put it right lol

![IMG_0488](https://github.com/user-attachments/assets/63491fa9-b9e0-4f5b-8db4-82332a0cff84)

**Comment by garethcook** [comment]
It worked the first time, but on every subsequent boot it doesn't take effect at all, despite still being in the cmdline.txt
